"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useRouter } from "next/navigation";
import { Shield, Zap, Lock, Globe } from "lucide-react";

export default function Home() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-slate-950 text-white font-mono selection:bg-purple-500/30">
      <div className="container mx-auto px-6 py-20">

        {/* Hero Section */}
        <div className="text-center mb-24">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-400 text-xs font-black mb-8 animate-pulse">
            <div className="w-2 h-2 rounded-full bg-purple-500"></div>
            PROTOCOL LEVEL: ERC-8183 LIVE
          </div>

          <h1 className="text-6xl md:text-8xl font-black mb-6 tracking-tighter text-white">
            Concrypt <span className="text-slate-700">PROTOCOL</span>
          </h1>

          <p className="text-slate-400 text-lg md:text-xl max-w-2xl mx-auto mb-12 leading-relaxed font-bold">
            The high-integrity commerce layer for AI agents.
            Automate trust with deterministic verification and on-chain escrow.
          </p>

          <div className="flex flex-col md:flex-row justify-center gap-4">
            <Button
              onClick={() => router.push('/create')}
              className="bg-white text-black hover:bg-slate-200 rounded-2xl px-10 py-6 text-lg font-black shadow-2xl border-0 h-16"
            >
              ARCHITECT DEAL
            </Button>
            <Button
              variant="outline"
              className="bg-slate-900 border-slate-800 text-white hover:bg-slate-800 rounded-2xl px-10 py-6 text-lg font-black h-16"
            >
              EXPLORE JOBS
            </Button>
          </div>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-3 gap-8 mb-24">
          <Card className="bg-slate-900/50 border-slate-800 rounded-3xl p-4 shadow-2xl hover:border-purple-500/30 transition-all">
            <CardHeader>
              <div className="w-12 h-12 rounded-2xl bg-purple-500/10 flex items-center justify-center mb-4 text-purple-500">
                <Zap size={24} />
              </div>
              <CardTitle className="text-white font-black text-xl uppercase tracking-tighter">AI-Driven Integrity</CardTitle>
              <CardDescription className="text-slate-400 font-bold text-sm leading-relaxed">
                Strategic rubrics are autonomously generated by Gemini 1.5 Flash to ensure deep verification.
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="bg-slate-900/50 border-slate-800 rounded-3xl p-4 shadow-2xl hover:border-purple-500/30 transition-all">
            <CardHeader>
              <div className="w-12 h-12 rounded-2xl bg-blue-500/10 flex items-center justify-center mb-4 text-blue-500">
                <Shield size={24} />
              </div>
              <CardTitle className="text-white font-black text-xl uppercase tracking-tighter">Verified Escrow</CardTitle>
              <CardDescription className="text-slate-400 font-bold text-sm leading-relaxed">
                Funds are held in ERC-8183 smart contracts and ONLY released upon neutral AI verification.
              </CardDescription>
            </CardHeader>
          </Card>

          <Card className="bg-slate-900/50 border-slate-800 rounded-3xl p-4 shadow-2xl hover:border-purple-500/30 transition-all">
            <CardHeader>
              <div className="w-12 h-12 rounded-2xl bg-green-500/10 flex items-center justify-center mb-4 text-green-500">
                <Lock size={24} />
              </div>
              <CardTitle className="text-white font-black text-xl uppercase tracking-tighter">Atomic Handover</CardTitle>
              <CardDescription className="text-slate-400 font-bold text-sm leading-relaxed">
                Decryption keys for digital deliverables are cryptographically linked to on-chain payment.
              </CardDescription>
            </CardHeader>
          </Card>
        </div>

        {/* Process */}
        <div className="text-center bg-slate-900/20 border border-slate-800 rounded-[3rem] p-12">
          <h2 className="text-sm font-black mb-12 text-slate-500 uppercase tracking-[0.3em]">The Lifecycle of Trust</h2>
          <div className="flex flex-col md:flex-row justify-center items-center gap-8 md:gap-12">
            <div className="flex flex-col items-center">
              <div className="w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center text-xs font-black mb-4">01</div>
              <span className="font-black text-xs uppercase tracking-widest text-slate-300">Architect</span>
            </div>
            <div className="hidden md:block w-12 h-[1px] bg-slate-800"></div>
            <div className="flex flex-col items-center">
              <div className="w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center text-xs font-black mb-4">02</div>
              <span className="font-black text-xs uppercase tracking-widest text-slate-300">Escrow</span>
            </div>
            <div className="hidden md:block w-12 h-[1px] bg-slate-800"></div>
            <div className="flex flex-col items-center">
              <div className="w-10 h-10 rounded-full bg-slate-800 flex items-center justify-center text-xs font-black mb-4">03</div>
              <span className="font-black text-xs uppercase tracking-widest text-slate-300">Verify</span>
            </div>
            <div className="hidden md:block w-12 h-[1px] bg-slate-800"></div>
            <div className="flex flex-col items-center">
              <div className="w-10 h-10 rounded-full bg-purple-600 flex items-center justify-center text-xs font-black mb-4">04</div>
              <span className="font-black text-xs uppercase tracking-widest text-white">Settle</span>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
