export const backendContractTemplate = {
  contracts: [
    {
      id: "contract_sample_001",
      contractHash: "0xsamplecontracthash",
      name: "Sample AI Service Agreement",
      projectType: "api_rental",
      description: "Reference contract illustrating all supported escrow options and metadata.",
      currentStage: "Signatures Pending",
      flowType: "execution",
      jurisdiction: {
        country: "India",
        countryCode: "IN",
        legalFramework: "Indian Contract Act, 1872",
        disputeResolution: "On-chain arbitration via Pakt Arbitration Network",
        applicableLaws: ["Indian Contract Act", "Information Technology Act", "Goods and Services Tax Act"],
        timezone: "Asia/Kolkata"
      },
      parties: {
        client: {
          name: "Acme Compute Pvt Ltd",
          email: "compute-ops@acme.com",
          walletAddress: "0x1111111111111111111111111111111111111111",
          role: "CLIENT",
          location: {
            country: "India",
            state: "Maharashtra",
            city: "Mumbai"
          }
        },
        freelancer: {
          name: "Nova GPU Services",
          email: "support@novagpu.ai",
          walletAddress: "0x2222222222222222222222222222222222222222",
          role: "FREELANCER",
          skills: ["GPU inference", "Model serving", "SLA monitoring"],
          location: {
            country: "India",
            state: "Karnataka",
            city: "Bengaluru"
          }
        }
      },
      signatures: {
        client: {
          signed: false,
          signedAt: null,
          signature: null
        },
        freelancer: {
          signed: false,
          signedAt: null,
          signature: null
        },
        bothSigned: false
      },
      escrow: {
        amounts: {
          inr: {
            totalAmount: "250000",
            currency: "INR",
            exchangeRateAt: "2025-10-08T10:00:00.000Z",
            exchangeRate: "85.00"
          },
          "POL": {
            totalAmount: "2941",
            currency: "POL",
            network: "POL-testnet"
          }
        },
        contractAddress: "0x3333333333333333333333333333333333333333",
        deposit: {
          deposited: false,
          depositedAmount: "0",
          depositedAt: null,
          transactionHash: null
        },
        fees: {
          platformFee: {
            inr: "6250",
            pol: "74"
          },
          storageFee: {
            inr: "1250",
            pol: "15"
          },
          totalFees: {
            inr: "7500",
            pol: "89"
          }
        }
      },
      storage: {
        contractDocument: {
          rootHash: "0xcontractdocumenthash",
          fileName: "contract_sample_001_signed.pdf",
          uploadedAt: null,
          uploadedBy: null,
          fileSize: "0"
        }
      },
      projectDetails: {
        deliverables: ["Dedicated inference endpoint", "SLA dashboard", "Weekly performance reports"],
        timeline: "90 days",
        startDate: "2025-10-10",
        endDate: "2026-01-08"
      },
      contractOptions: {
        escrowType: "time_locked_inference",
        arbitrationPreference: "Pakt Arbitration Network (default)",
        arbitrationContract: "0x4444444444444444444444444444444444444444",
        vaultOptIn: true
      },
      precompiledContract: {
        key: "timeLockedEscrow",
        displayName: "Time-Locked Inference Escrow",
        targetNetwork: "POL-testnet",
        deploymentStatus: "not_deployed",
        constructorParameters: {
          client: "0x1111111111111111111111111111111111111111",
          provider: "0x2222222222222222222222222222222222222222",
          agent: "0x5555555555555555555555555555555555555555",
          arbitration: "0x4444444444444444444444444444444444444444",
          vault: "0xa570E01A19A4bE995f5A27498b22eC6CbC2F1283",
          durationSeconds: 604800,
        },
        artifactStatus: {
          abi: "available",
          bytecode: "available"
        }
      },
      serviceMonitoring: {
        serviceDuration: "120 hours of GPU runtime",
        apiEndpoint: "https://api.novagpu.ai/v1/inference",
        uptimeSLA: "99.5% availability, <150ms p95 latency"
      },
      financialInfo: {
        basePaymentInInr: "250000",
        basePaymentInPOL: "2941",
        escrowYieldRate: "1%",
        computedYieldShare: {
          client: "90%",
          freelancer: "10%"
        }
      },
      legalContract: {
        contractText: "Reference legal contract text generated by Pakt AI.",
        generatedAt: "2025-10-10T08:00:00.000Z",
        generatedBy: "POL_Compute_TEE",
        storageRootHash: "0xlegalroot",
        verificationProof: {
          type: "TEE",
          hash: "0xverificationhash",
          timestamp: "2025-10-10T08:00:00.000Z"
        }
      },
      milestones: [],
      timeLockedEscrow: {
        contractAddress: null,
        provider: {
          name: "Nova GPU Services",
          walletAddress: "0x2222222222222222222222222222222222222222",
          apiEndpoint: "https://api.novagpu.ai/v1/inference"
        },
        agent: "0x5555555555555555555555555555555555555555",
        client: "0x1111111111111111111111111111111111111111",
        arbitrationContract: "0x4444444444444444444444444444444444444444",
        vaultAddress: "0xa570E01A19A4bE995f5A27498b22eC6CbC2F1283",
        tokens: {
          fundedAmount: "2941",
          fundedAt: null,
          lastClaimedAt: null
        },
        service: {
          duration: "90 days",
          durationSeconds: 7776000,
          startedAt: null,
          paused: false,
          pausedAt: null,
          resumeAt: null
        }
      },
      currentMilestone: null,
      agentInfo: {
        iNFTContractAddress: "0x5555555555555555555555555555555555555555",
        iNFTTokenId: "90001",
        lastAction: null
      },
      stageHistory: [
        {
          stage: "Jurisdiction Selected",
          timestamp: "2025-10-10T08:00:00.000Z",
          triggeredBy: "user",
          note: "India selected as jurisdiction"
        },
        {
          stage: "Information Complete",
          timestamp: "2025-10-10T08:05:00.000Z",
          triggeredBy: "system",
          note: "All required fields collected via graph loop"
        },
        {
          stage: "Signatures Pending",
          timestamp: "2025-10-10T08:06:00.000Z",
          triggeredBy: "system",
          note: "Contract generated and awaiting signatures"
        }
      ],
      shareableLink: "https://Pakt.com/contracts/contract_sample_001",
      createdAt: "2025-10-10T08:00:00.000Z",
      lastUpdated: "2025-10-10T08:06:00.000Z",
      status: "ACTIVE"
    }
  ]
};
